#!/bin/bash

# set reasonable defaults for msmtp

MSMTP_SERVER=${SSMTP_SERVER:-mailhog}
MSMTP_PORT=${SSMTP_PORT:-1025}

cat << EOF > /etc/msmtprc
# Set defaults.
defaults
# Enable or disable TLS/SSL encryption.
tls on
tls_starttls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
# Setup WP account's settings.
account 
host $MSMTP_SERVER
port $MSMTP_PORT
auth off
user 
password 
from 
logfile /var/log/msmtp/msmtp.log

account default : 

EOF

# Change Apache document root if needed
APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT:-/var/www/html}
if [[ $APACHE_DOCUMENT_ROOT != "/var/www/html" ]]
	then
		sed -ri -e "s|/var/www/html|${APACHE_DOCUMENT_ROOT}|g" /etc/apache2/sites-available/*.conf
fi


# https://github.com/docker-library/php/blob/master/7.3/buster/apache/docker-php-entrypoint
# Add default official image command

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"